### ISSUE TITLE
Question about CyclicLR - optimizer 

### ISSUE THREAD

**Issue by trevor-taeyeop** [ethnhe/PVN3D#2]
Hi, Tethnhe.
Thanks for sharing a good result. 

I just follow your process but got a simple error.
Could you share how to solve this error message?? 

> **Error from this part**:
> https://github.com/ethnhe/PVN3D/blob/290262b8f9e682a40c2b075e7a8b6feda6f577ca/pvn3d/train/train_ycb_pvn3d.py#L466

> **Error Message**: 
> 
> root@0522615bcc7b:~/PVN3D/pvn3d# sh eval_ycb.sh 
> test_dataset_size:  2949
> loading pretrained mdl.
> ==> Loading from checkpoint '/root/PVN3D/pvn3d/train_log/ycb/checkpoints/ycb_pvn3d_best.pth.tar'
> ==> Done
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/PVN3D/pvn3d/train/train_ycb_pvn3d.py", line 468, in <module>
>     mode = 'triangular'
>   File "/root/PVN3D/pvn3d/lib/utils/warmup_scheduler/scheduler.py", line 240, in __init__
>     super().__init__(optimizer)
>   File "/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py", line 77, in __init__
>     self.step()
> TypeError: step() missing 1 required positional argument: 'step'

**Comment by ethnhe** [comment]
Which version of PyTorch you are using? It works well with pytorch==1.0.1.post2.

**Comment by trevor-taeyeop** [comment]
I use python 3.6.8, torch==1.4.0

**Comment by trevor-taeyeop** [comment]
I used torch version 1.4 and changed to 1.0.1.post2. 

I got a different error.

root@843c6acaa892:~/PVN3D/pvn3d# ./eval_ycb.sh 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/PVN3D/pvn3d/train/train_ycb_pvn3d.py", line 22, in <module>
    from lib.utils.etw_pytorch_utils.viz import *
  File "/root/PVN3D/pvn3d/lib/__init__.py", line 8, in <module>
    from .pvn3d import PVN3D
  File "/root/PVN3D/pvn3d/lib/pvn3d.py", line 13, in <module>
    from lib.pointnet2_utils.pointnet2_modules import PointnetFPModule, PointnetSAModuleMSG
  File "/root/PVN3D/pvn3d/lib/pointnet2_utils/__init__.py", line 8, in <module>
    from . import pointnet2_utils
  File "/root/PVN3D/pvn3d/lib/pointnet2_utils/pointnet2_utils.py", line 19, in <module>
    from lib.pointnet2_utils import _ext
ImportError: /root/PVN3D/pvn3d/lib/pointnet2_utils/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

**Comment by ethnhe** [comment]
You need to reinstall the PointNet++ after you change the torch version by:
python3 setup.py build_ext

**Comment by trevor-taeyeop** [comment]
I already did that process and there was no error in python3 setup.py build_ext

root@843c6acaa892:~/PVN3D# python3 setup.py build_ext
running build_ext
./build/lib.linux-x86_64-3.6/pointnet2_utils/_ext.cpython-36m-x86_64-linux-gnu.so ==> pvn3d/lib/pointnet2_utils/_ext.cpython-36m-x86_64-linux-gnu.so
root@843c6acaa892:~/PVN3D# cd  pvn3d/
root@843c6acaa892:~/PVN3D/pvn3d# ./eval_ycb.sh 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/PVN3D/pvn3d/train/train_ycb_pvn3d.py", line 22, in <module>
    from lib.utils.etw_pytorch_utils.viz import *
  File "/root/PVN3D/pvn3d/lib/__init__.py", line 8, in <module>
    from .pvn3d import PVN3D
  File "/root/PVN3D/pvn3d/lib/pvn3d.py", line 13, in <module>
    from lib.pointnet2_utils.pointnet2_modules import PointnetFPModule, PointnetSAModuleMSG
  File "/root/PVN3D/pvn3d/lib/pointnet2_utils/__init__.py", line 8, in <module>
    from . import pointnet2_utils
  File "/root/PVN3D/pvn3d/lib/pointnet2_utils/pointnet2_utils.py", line 19, in <module>
    from lib.pointnet2_utils import _ext
ImportError: /root/PVN3D/pvn3d/lib/pointnet2_utils/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

**Comment by ethnhe** [comment]
How about remove the /root/PVN3D/build/ folder and the  /root/PVN3D/pvn3d/lib/pointnet2_utils/_ext.cpython-36m-x86_64-linux-gnu.so and then rebuild PointNet++ again? It seems that the build process is not triggered when you run python3 setup.py build_ext.

**Comment by trevor-taeyeop** [comment]
I try your advice. It still has the same problem.

**Comment by ethnhe** [comment]
Strange then. You can try torchvision==0.2.2. Or you can try to build the _ext module from https://github.com/erikwijmans/Pointnet2_PyTorch and then move the built .so file to  ``PVN3D/pvn3d/lib/pointnet2_utils/``. The code of the PointNet++ is referenced from that repo.
